### ISSUE TITLE
L9 Support

### ISSUE THREAD

**Issue by invaders-xx** [patricksamson/laravel-countries#19]
Trying to install on L9 and get:
Problem 1
    - Root composer.json requires lykegenes/laravel-countries ^2.0 -> satisfiable by lykegenes/laravel-countries[2.0.0].
    - lykegenes/laravel-countries 2.0.0 requires illuminate/support ^5.8|^6.0|^7.0|^8.0 -> found illuminate/support[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

How can I make it working ?

**Comment by patricksamson** [comment]
[This open PR](https://github.com/mledoze/countries/pull/450/files) on the data source dependency [mledoze/countries](https://github.com/mledoze/countries) prevents Laravel 9 support.
I could probably remove the direct dependency and modify my compiler script to use the Github URL pointing to the file I need instead.

**Comment by patricksamson** [comment]
Fixed in #20 and tagged a new release, should work right out of the box!

**Comment by invaders-xx** [comment]
Thank you but I am not able to retrieve the 2.0.1 version, even after a composer clear-cache, it's trying to retrieve 2.0 version. Event if I force the version I got " Could not find package lykegenes/laravel-countries in a version matching 2.0.1"
